-- 8.	Enable the constraint on CustomerId of the Customer table, and see the message generated by the Oracle server. 
 
	   Alter table cust_table add constraints Custid_prim PRIMARY KEY (customerid);